# Generated by Django 4.2.5 on 2023-09-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argue', '0003_premise_conclusion_argument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conclusion',
            name='premise',
        ),
        migrations.AddField(
            model_name='conclusion',
            name='premises',
            field=models.ManyToManyField(to='argue.premise'),
        ),
    ]
